alias ssh='ssh -A'
alias sshagent='ssh-agent -s; ssh-add ~/.ssh/bb_id_rsa'
alias grep='grep --color'
alias vimrc='cd ~/vimrc/'
alias ps='ps -ww'
alias xcopy='xclip -selection clipboard'
alias xpaste='xclip -selection clipboard -o'
